version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 10
  target-branch: withMaxNodeModulesJsDepth
